# Generated by Django 5.2.2 on 2025-06-15 02:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('timestamp', models.DateTimeField()),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('xgBoost_SHAP', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transaction_history',
                'indexes': [models.Index(fields=['symbol'], name='transaction_symbol_161166_idx'), models.Index(fields=['timestamp'], name='transaction_timesta_828cf8_idx'), models.Index(fields=['order_id'], name='transaction_order_i_78a6e8_idx')],
            },
        ),
    ]
