# Generated by Django 5.2.2 on 2025-06-15 04:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentHoldings',
            fields=[
                ('holdings_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('net_quantity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('avg_cost_basis', models.DecimalField(decimal_places=6, max_digits=15)),
                ('total_invested', models.DecimalField(decimal_places=2, max_digits=15)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('first_purchase_date', models.DateTimeField()),
                ('last_transaction_date', models.DateTimeField()),
                ('number_of_transactions', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'current_holdings',
                'indexes': [models.Index(fields=['symbol'], name='current_hol_symbol_b68ec8_idx'), models.Index(fields=['is_active'], name='current_hol_is_acti_48c628_idx'), models.Index(fields=['last_transaction_date'], name='current_hol_last_tr_f48f33_idx')],
            },
        ),
    ]
