# Generated by Django 5.2.2 on 2025-06-15 04:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_currentholdings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='sentiment_score',
            new_name='finbert_sentiment',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='xgBoost_SHAP',
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='regime_sentiment',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='xgboost_shap',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MLFeatures',
            fields=[
                ('feature_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('rsi_14', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bb_upper', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('bb_lower', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('bb_middle', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('sma_20', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('sma_50', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('ema_12', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('ema_26', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('finbert_sentiment', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('regime_sentiment', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('news_sentiment', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('vix_level', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('market_regime', models.CharField(blank=True, max_length=20, null=True)),
                ('strategy_used', models.CharField(blank=True, max_length=50, null=True)),
                ('strategy_signal_strength', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('xgboost_shap_values', models.JSONField(blank=True, null=True)),
                ('model_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('decision_reasoning', models.TextField(blank=True, null=True)),
                ('custom_features', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features', to='database.transactionhistory')),
            ],
            options={
                'db_table': 'ml_features',
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='ml_features_symbol_f9d9bd_idx'), models.Index(fields=['timestamp'], name='ml_features_timesta_923179_idx'), models.Index(fields=['transaction'], name='ml_features_transac_4d1758_idx'), models.Index(fields=['strategy_used'], name='ml_features_strateg_dd403c_idx')],
            },
        ),
    ]
