# Generated by Django 5.2.2 on 2025-06-19 16:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_rename_sentiment_score_transactionhistory_finbert_sentiment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentholdings',
            name='realized_pnl',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=15),
        ),
        migrations.CreateModel(
            name='TradingWatchlist',
            fields=[
                ('watchlist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('HOLDING', 'Currently Holding'), ('WATCHING', 'Watching for Entry'), ('ANALYZING', 'Under Analysis'), ('BLACKLIST', 'Temporarily Blacklisted'), ('SOLD', 'Recently Sold - Monitoring')], default='WATCHING', max_length=20)),
                ('priority', models.IntegerField(default=5)),
                ('monitor_frequency', models.IntegerField(default=60)),
                ('target_entry_price', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('stop_loss_price', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('take_profit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('max_position_size_pct', models.DecimalField(decimal_places=2, default='10.00', max_digits=5)),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('news_sentiment', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('technical_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('preferred_strategies', models.JSONField(blank=True, default=list)),
                ('blacklisted_strategies', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('sector', models.CharField(blank=True, max_length=50)),
                ('market_cap', models.CharField(blank=True, max_length=20)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('last_analyzed', models.DateTimeField(blank=True, null=True)),
                ('last_price_check', models.DateTimeField(blank=True, null=True)),
                ('last_news_check', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('analysis_count', models.IntegerField(default=0)),
                ('alert_triggered_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_holding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchlist_entry', to='database.currentholdings')),
            ],
            options={
                'db_table': 'trading_watchlist',
                'ordering': ['-priority', 'symbol'],
                'indexes': [models.Index(fields=['symbol'], name='trading_wat_symbol_49e276_idx'), models.Index(fields=['status'], name='trading_wat_status_25f231_idx'), models.Index(fields=['priority', 'is_active'], name='trading_wat_priorit_a874ec_idx'), models.Index(fields=['last_analyzed'], name='trading_wat_last_an_88cfd2_idx'), models.Index(fields=['sector'], name='trading_wat_sector_f3a24b_idx')],
            },
        ),
    ]
