# Generated by Django 5.2.3 on 2025-07-12 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_create_coordination_config'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='currentholdings',
            new_name='current_hol_current_f32b73_idx',
            old_name='database_cur_current_4b72d4_idx',
        ),
        migrations.RenameIndex(
            model_name='currentholdings',
            new_name='current_hol_assignm_e3f2fd_idx',
            old_name='database_cur_assignm_5a8e7c_idx',
        ),
        migrations.RenameIndex(
            model_name='currentholdings',
            new_name='current_hol_strateg_d500d1_idx',
            old_name='database_cur_strateg_9f3b2a_idx',
        ),
    ]
